### PR TITLE
feat(codex): initial setup and implementation

### PR DESCRIPTION
**Pull request by mgan59**
## Context

Initial Codex work and setting up the ADR Process.  There were some adjustments to the implementation to account for the `unified@10.x` upgrade as noted in the rendered: [ADR-002](https://github.com/gitbabel/gitbabel-platform/blob/issue-2-setup-initial-codex/docs/adrs/0002-initial-implementation-for-unified-and-remark.md).

Otherwise Includes:

- Setup of `codex/src/index.js` that has our initial `process` function that wraps `unified/remark`
- Setup of Jest

### CODE REVIEW

**Comment by mgan59** [comment]
Additional reading for ADR-002 -- https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1

**Comment by JSheleg** [comment]
👍🏻

**Comment by AlexanderHeo** [comment]
👍

**Comment by JSheleg** [comment]
👎🏻

**Comment by plaetzaw** [comment]
Nothing catastrophic here, aokay.

**Pull request merged**
